version: "3.9"

services:
  db:
    image: postgres:16.4-alpine
    container_name: "todos-database"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - database_postgres:/var/lib/postgresql/data
    healthcheck :
      test: [ "CMD", "pg_isready", "-d", "postgres", "-U", "postgres" ]
      interval : 5s
      timeout : 5s
      retries : 5

  api:
    build: .
    container_name: "todos"
    environment:
      DB_URL: "postgres://postgres:password@db:5432/postgres?sslmode=disable"
      PORT: "3000"
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy

volumes:
  database_postgres:
